spring:
  application:
    name: Spring Boot Security Training
  profile:
    active: local

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:h2db
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


